KRK_ASP_Sroda_12/ViewModels/SylabusViewModel.cs
using KRK_ASP_Sroda12.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KRK_ASP_Sroda_12.ViewModels
{
    public class SylabusViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Nazwa przedmiotu")]
        public string SubjectName { get; set; }

        [Required]
        [Display(Name = "Kod przedmiotu")]
        public string SubjectCode { get; set; }

        [Display(Name = "Typ przedmiotu")]
        public SubjectType SubjectType { get; set; }

        [Display(Name = "Kierunek")]
        public int SelectedFieldOfStudyId { get; set; }

        public SelectList FieldOfStudies { get; set; }
    }
}

KRK_ASP_Sroda_12/Controllers/SylabusController.cs
using KRK_ASP_Sroda_12.Models;
using KRK_ASP_Sroda_12.ViewModels;
using KRK_ASP_Sroda12.Models;
using KRK_ASP_Sroda12.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace KRK_ASP_Sroda_12.Controllers
{
    [Authorize]
    public class SylabusController : Controller
    {
        IRepositoryService<Sylabus> _sylabusService;
        Lazy<IRepositoryService<FieldOfStudy>> _fieldOfStudyService;


        public SylabusController(IRepositoryService<Sylabus> sylabusService,
            Lazy<IRepositoryService<FieldOfStudy>> fieldOfStudyService
            )
        {
            _sylabusService = sylabusService;
            _fieldOfStudyService = fieldOfStudyService;
        }

        public ActionResult Index(int? FieldOfStudyId)
        {
            var sylabuses = _sylabusService.GetAll();

            if(FieldOfStudyId != null)
            {
                sylabuses.Where(x => x.FieldOfStudy_Id == FieldOfStudyId);
            }

            SylabusIndexViewModel viewModel = new SylabusIndexViewModel()
            {
                FieldOfStudies = new SelectList(_fieldOfStudyService.Value.GetAll(), "Id", "Name"),
                Items = sylabuses
                .ToList()
                .Select(r => AutoMapper.Mapper.Map<SylabusIndexItemViewModel>(r))
                .ToList()
            };

            return View(viewModel);
        }

        // GET: Sylabus/Create
        public ActionResult Create()
        {
            SylabusViewModel viewModel = new SylabusViewModel(){ FieldOfStudies = new SelectList(_fieldOfStudyService.Value.GetAll(), "Id", "Name") };
            return View(viewModel);
        }

        // POST: Sylabus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SylabusViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var sylabusToCreate = new Sylabus();

                AutoMapper.Mapper.Map<SylabusViewModel, Sylabus>(viewModel, sylabusToCreate);

                var result = _sylabusService.Add(sylabusToCreate);

                if (result.Result == ServiceResultStatus.Succes)
                {
                    return RedirectToAction("Index");
                }

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        public ActionResult Edit(int? id)
        {
            if (id.HasValue)
            {
                var sylabusToEdit = _sylabusService.GetSingle(id.Value);

                if (sylabusToEdit != null)
                {
                    SylabusViewModel viewModel = AutoMapper.Mapper.Map<SylabusViewModel>(sylabusToEdit);
                    viewModel.SelectedFieldOfStudyId = sylabusToEdit.FieldOfStudy_Id;

                    return View(viewModel);
                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SylabusViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var sylabusToEdit = _sylabusService.GetSingle(viewModel.Id);
                if (sylabusToEdit != null)
                {
                    AutoMapper.Mapper.Map<SylabusViewModel, Sylabus>(viewModel, sylabusToEdit);
                    sylabusToEdit.FieldOfStudy_Id = viewModel.SelectedFieldOfStudyId;

                    //sylabusToEdit.SubjectName = viewModel.SubjectName;
                    //sylabusToEdit.SubjectCode = viewModel.SubjectCode;
                    //sylabusToEdit.SubjectType = viewModel.SubjectType;

                    var result = _sylabusService.Edit(sylabusToEdit);

                    if (result.Result == ServiceResultStatus.Succes)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }

            return View(viewModel);
        }

        // GET: Sylabus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Sylabus sylabus = _sylabusService.GetSingle(id.Value);
            SylabusViewModel viewModel = AutoMapper.Mapper.Map<SylabusViewModel>(sylabus);
            if (sylabus == null)
            {
                return HttpNotFound();
            }
            return View(viewModel);
        }


        // GET: Sylabus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var sylabusToDelete = _sylabusService.GetSingle(id.Value);
            if (sylabusToDelete == null)
            {
                return HttpNotFound();
            }

            SylabusViewModel viewModel = AutoMapper.Mapper.Map<SylabusViewModel>(sylabusToDelete);
            return View(viewModel);
        }

        // POST: Sylabus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var sylabusToDelete = _sylabusService.GetSingle(id);
            _sylabusService.Delete(sylabusToDelete);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            // if(disposing)
            // context.Dispose();

            base.Dispose(disposing);
        }
    }
}

KRK_ASP_Sroda_12/Views/Sylabus/Create.cshtml
@model KRK_ASP_Sroda_12.ViewModels.SylabusViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sylabus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SubjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubjectCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubjectCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.SubjectType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedFieldOfStudyId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectedFieldOfStudyId, Model.FieldOfStudies, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SelectedFieldOfStudyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KRK_ASP_Sroda_12/Views/Sylabus/Delete.cshtml
@model KRK_ASP_Sroda_12.ViewModels.SylabusViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sylabus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SubjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubjectCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubjectCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubjectType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubjectType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KRK_ASP_Sroda_12/Views/Sylabus/Details.cshtml
@model KRK_ASP_Sroda_12.ViewModels.SylabusViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Sylabus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SubjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubjectCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubjectCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubjectType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubjectType)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KRK_ASP_Sroda_12/Views/Sylabus/Edit.cshtml
@model KRK_ASP_Sroda_12.ViewModels.SylabusViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SylabusViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubjectCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubjectCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.SubjectType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedFieldOfStudyId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectedFieldOfStudyId, Model.FieldOfStudies, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót do listy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KRK_ASP_Sroda_12/Views/Sylabus/Index.cshtml
@model KRK_ASP_Sroda_12.ViewModels.SylabusIndexViewModel


@{
    ViewBag.Title = "Index";
}   

<h2>Index</h2>

@using (Html.BeginForm("Index", "Sylabus", FormMethod.Get))
{

    <div class="form-horizontal">
        <h4>Sylabus</h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.FieldOfStudyId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FieldOfStudyId, Model.FieldOfStudies, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FieldOfStudyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Filtruj" class="btn btn-default" />
            </div>
        </div>
    </div>
}
d
<p>
    @Html.ActionLink("Nowy", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Nazwa przedmiotu")
        </th>
        <th>
            @Html.DisplayName("Symbol")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Items) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SubjectName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SubjectCode)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }, new {@class="btn btn-primary" }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }, new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }, new { @class = "btn btn-primary" })
        </td>
    </tr>
}

</table>